
---
# playbook.yml
- name: 'Provision Image'
  hosts: default
  become: true

  tasks:
    - name: install nginx 
      package:
        name: 'nginx'
        state: present
    - name: install php 
      apt:
        pkg:
         - php-fpm 
         - php-sqlite3 
         - php-xml 
         - php-curl
         - composer 
        state: latest
        update_cache: true      
    - name: Composer install
      composer: 
        command: install 
        working_dir: /var/www/html
        register: result
      ignore_errors: true
      environment:
        COMPOSER_NO_INTERACTION: "1"
    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: result
        verbosity: 2
    - name: update permissions
      file: dest=/var/www/html owner=www-data group=www-data
    - name: Template nginx config file 
      ansible.builtin.template:
        src: nginx-symfony.conf.j2
        dest: /etc/nginx/sites-available/default 
