
---
# playbook.yml
- name: 'Provision Image'
  hosts: default
  become: true

  tasks:
    - name: install nginx 
      package:
        name: 'nginx'
        state: present
    - name: install php-fpm 
      package:
        name: 'php-fpm'
        state: present
    - name: Template nginx config file 
      ansible.builtin.template:
        src: nginx-symfony.conf.j2
        dest: /etc/nginx/sites-available/default 
